# Generated by Django 6.1 on 2026-08-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_enable_vector_extension'),
    ]

    operations = [
    ]
