# Generated by Django 6.1 on 2026-08-29 05:08

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_enable_vector_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=50)),
                ('ads_speed_modifier', models.FloatField(default=0.0)),
                ('recoil_modifier', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('base_damage', models.FloatField()),
                ('base_fire_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tactical_description', models.TextField(help_text='LLM generated summary of the build')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.ManyToManyField(blank=True, to='api.attachment')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weapon')),
            ],
        ),
    ]
