# Generated by Django 6.1 on 2026-08-31 09:34

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='category',
            new_name='weapon_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='ads_speed_modifier',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='recoil_modifier',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='base_damage',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='base_fire_rate',
        ),
        migrations.AlterField(
            model_name='loadout',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loadout',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='loadout',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadouts', to='api.weapon'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
