# Generated by Django 6.1 on 2026-08-31 10:06

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_category_weapon_weapon_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loadout',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='loadout_embedding_index', opclasses=['vector_cosine_ops']),
        ),
    ]
