# Generated by Django 6.1 on 2026-08-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_loadout_loadout_embedding_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapons', to='api.weaponcategory'),
        ),
    ]
