# backend/api/migrations/0007_add_attachment_stat_modifiers.py
# Generated by Django 6.1 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_weaponcategory_alter_weapon_weapon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='damage_modifier',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attachment',
            name='ads_modifier',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attachment',
            name='recoil_modifier',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='slot',
            field=models.CharField(choices=[('Muzzle', 'Muzzle'), ('Barrel', 'Barrel'), ('Optic', 'Optic'), ('Underbarrel', 'Underbarrel'), ('Magazine', 'Magazine'), ('Stock', 'Stock')], max_length=50),
        ),
    ]