# backend/api/migrations/0008_unique_attachment_name_slot.py
# Generated by Django 6.1 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_attachment_stat_modifiers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=['name', 'slot'], name='unique_attachment_name_slot'),
        ),
    ]